version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clients_data
      - DB_USER=alfa_user
      - DB_PASSWORD=alfa_password
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=clients_data
      - POSTGRES_USER=alfa_user
      - POSTGRES_PASSWORD=alfa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_client_data_table.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  postgres_data:
